### ISSUE TITLE
Immutable OpenBSD on AWS

### ISSUE THREAD

**Issue by sarnowski** [ajacoutot/aws-openbsd#27]
I would like to introduce you to a new imaginary tool called `create-immutable-openbsd-ami`. This tool creates OpenBSD AMIs on AWS with an immutable design. Just like mine, many companies use immutable AMIs to spin up servers in the cloud. Preprovisioned systems have some advantages in dynamic clouds like playing much nicer with tools like AWS AutoScaling Groups and allow you to lock down systems from boot on.

This new imaginary tool has a `--help` output like this:

```
Usage: create-immutable-openbsd-ami [options]

Options:
  --mirror      The OpenBSD mirror to download packages from. Look up mirrors at
                https://www.openbsd.org/ftp.html.
                Example: "https://ftp.example.org/pub/OpenBSD/" [required]
  --release     The OpenBSD release like "6.1" or special case "snapshot".
  --sets        A comma separated list of OpenBSD sets to install.
                Defaults to: base,comp,game,man,xbase,xfont,xserv,xshare
  --packages    A comma separated list of packages to install. Packages will be fetched
                from the given mirror. Also supports  referencing build-local packages
                like "./mypackage-1.0.tgz" or remote packages like
                "https://example.com/mypackage-1.0.tgz".
  --root-size   Size of the root partition. Defaults to 1G. Might be tuned to save space
                or to increase space to install more packages.
  --overlay     References a build-local directory which will be copied over to the AMI
                (and replacing potential existing files). Commonly used to provision the
                "/etc/rc.conf.local" file and similar configurations.
  --postexec    A build-local file that will be executed after all build steps on the
                final AMI filesystem to provide generic provisioning capabilities in
                case the other options weren't sufficient.

Examples:

Build the default OpenBSD AMI:

    create-immutable-openbsd-ami --mirror https://ftp.example.org/pub/OpenBSD/ \
                                 --release 6.1

Build the most minimal OpenBSD AMI possible (but with documentation):

    create-immutable-openbsd-ami --mirror https://ftp.example.org/pub/OpenBSD/ \
                                 --release 6.1 \
                                 --sets base,man

Build an OpenBSD AMI with Java available:

    create-immutable-openbsd-ami --mirror https://ftp.example.org/pub/OpenBSD/ \
                                 --release 6.1 \
                                 --packages jdk-1.8

Build an AMI that runs "httpd" by default:

    mkdir -p files/etc

    cat > files/etc/rc.conf.local << "EOF"
    httpd_flags=""
    EOF
    
    create-immutable-openbsd-ami --mirror https://ftp.example.org/pub/OpenBSD/ \
                                 --release 6.1 \
                                 --overlay ./files
```

Using this imaginary tool would create an AWS AMI with the desired setup. The resulting disk layout would look like this:

```
# cat /etc/fstab
/dev/sd0a   /      ffs     ro                        0   1
none        /tmp   tmpfs   rw,-s100M                 0   0
/dev/sd0b   /var   ffs     rw,softdep,nodev,nosuid   1   2
```

On boot, the AMI would resize the `/var` partition up to the full size that the root disk has free. Since everything except `/var` will be read-only, home directories of human users need to link to the writeable partition:

```
/root  ->  /var/root
/home  ->  /var/home
```

`swap` is not desired on cloud instances (very opinionated..). `cloud-init` like initialization is (almost) independent of this tool and should be installed as a package if desired. Generation of SSH server keys needs some thoughts - a mini partition of 1M could be created and mounted for persistent storage of keys, the key directory could be just linked to `/var` as home directories or the directory will mount a tmpfs, assuming that servers are not restarted/reused in an immutable infrastructure anyway.

All of that can be made pretty generic as almost nothing of it is cloud dependent. AWS specific pieces can be modularized and also potentially extended for other cloud providers.

## Why are you telling me this?

This repository contains a great tool to bootstrap OpenBSD AWS AMIs. I am very excited about this possibility and want to pick it up. The current tool creates very generic AMIs that resemble a default OpenBSD installation. This is great in order to offer the most flexibility. It covers a lot of details and will most likely add further tweaks and tricks in the future for optimal cloud operations.

I would like to create a more opinionated AMI design for my operations as described here. But I would like to avoid reinventing the wheel. With this request I would like to open a discussion what the right way to approach this is. Is it desired by you to make your tooling more extendable and configurable or is setting up a dedicated tool a better way to explore this path? Have you any interest in this kind of undertaking to begin with?

Thanks for your great work!

**Comment by reyk** [comment]
Hi, so an _imaginary tool_ means that it doesn't exist?

You can already use the userdata as an overlay option to deploy custom VMs from generic AMIs (just embed the files as heredocs or shell archive in the userdata script).

Antoine and me are currently experimenting with different ways to create __*Open*BSD__ VMs, but I think we're both trying to create something that matches the default OpenBSD installation as closely as possible.

A few comments:

* I agree that `swap` should be disabled on the main OS disk - it is even a requirement for marketplace VMs. Some machine types in AWS and all VM sizes in Azure offer ephemeral/resource disks that can be used for `swap`.
* It is not recommended to simplify the filesystem layout. We have certain mount options (eg. `wxallowed` on `/usr/local`) and assumptions on OpenBSD's auto-layout. OpenBSD supports simplified layouts like a single partition but you have been warned that they are less secure.
* We are even considering the opposite: auto-installing AMIs. The problem with pre-provisioned VM images is that they all have the same randomisation in the filesystem, kernel, and libraries where the installer usually makes each installation unique. This contradicts of what the project is doing with efforts like KARL (http://undeadly.org/cgi?action=article&sid=20170701170044).
* I don't get the benefits of using the `tmpfs` hackery here if you don't intend to reboot the server. These things are usually done for appliances that have to be fail-safe on power loss. Also the generation of server keys has been solved in OpenBSD: it is done when you start your newly-installed system for the first time. cloud-init implementations like `ec2-init.sh` or `cloud-agent` print the host key fingerprints on first boot.
* We usually don't use --long-options in OpenBSD ;-)

I agree that such immutable images would be helpful for specific use cases, but people have to know these implications. After all, running any kind of software in a public cloud is already some kind of a security compromise, isn't it? But we're still trying to get the best out of OpenBSD.

**Comment by ajacoutot** [comment]
@sarnowski to add to what @reyk said, once you have access to working OpenBSD AMI, it's easy to modify it to your specific needs using tools like packer (https://www.packer.io/), which is also available as a port :-)
I'd rather concentrate on providing a generic OpenBSD cloud image that would match a standard installation as much as possible while still being cloud-friendly.
There's still some ongoing discussion about the best way to do that.

**Comment by sarnowski** [comment]
Thanks for your answers. I took some time to prototype what I described and looked at all your code. I think that using packer is a valid compromise to prevent me chasing your tunings ;-) As I wrote before, I know and agree that you want to provide a vanilla/default AMI.

I figured out the aspects why I came up with this issue to begin with. You actually do some choices for the user that are not bound to the default installation:

* Sets: You install all sets automatically. I often don't need more than `base` and `man`. I almost never need `comp` and `games` and only sometimes need the `x*` sets (for example for Java). I think it would be trivial to allow customization here. Either provide this as an option in this tool to select the sets so that I could create my own base AMIs or also provide a minimal AMI that I can extend with the other sets if required. (probably providing a "full" AMI or a "minimal" AMI) The problem with all the unnecessary sets is that I need to apply security updates for compliance even if those tools are not in use. _This is not a showstopper_ but it would feel "cleaner" to not have that stuff on the server (as I do on onpremise boxes as well)
* Partition setup: You made your point about the default partitioning scheme. There is one important aspect for me: auto resizing. As far as I can tell, this is not implemented yet in the ec2-init script. As I am using EC2 instances exclusively for server workloads, the size of `/var` matters the most. If I choose an EBS volume size for my disk, I align that with the space needs I have in `/var`. Will you implement auto resizing? From my vague understanding of OpenBSD's initialization procedure, there is no natural way to hook such a functionality in right now. Not having this functionality is a showstopper for me.

The vague comment about auto-installing VMs sounds very obscure but also interesting ;-) My interpretation of that statement is that you would actually want to do the installation on boot of the VM. This would of course give the opportunity to dynamically implement the two features I mentioned very naturally (no resizing of partition after the fact). Is there some more information about your plans?

**Comment by sarnowski** [comment]
Do you think of something like http://man.openbsd.org/autoinstall.8 ? That sounds like a good idea as a first impression. Most questions can probably be answered by the AWS environment (like user, ssh key, ...).

**Comment by reyk** [comment]
Not fully related to [aws-openbsd](https://github.com/ajacoutot/aws-openbsd), but I'm hijacking this issue to ponder about the options.

I can think of three methods to make new VM instances more "unique" and I'm intending to implement all of them to figure out what works best. I also think that running syspatch on -stable VMs is a good idea too because we could avoid that a new instance spawns up with a potentially unpatched kernel, web server, or sshd. Running automatic syspatch in AWS for 6.1 with 14 patches currently takes about 1.5 minutes, see `time` output in dmesg below.

1. Running some initialization from the standard rc script on first boot. The `/etc/rc.sysmerge` file seems to provide a good place to do such things. I tested a simple version that runs a) KARL (creating a unique kernel on -current) and b) syspatch (installing updates on -stable).
See https://github.com/reyk/cloud-openbsd/commit/db1fd8b1888a040c50504954f9eaffb0a87715c2.

2. Running a custom `/etc/rc` script on first boot before anything else. This is slightly more complicated but allows to do more first boot actions, including a) KARL, b) syspatch, c) randomization of inode generations number (using [fsirand(8)](https://man.openbsd.org/fsirand.8) instead of the randomization in newfs). See https://github.com/reyk/cloud-openbsd/commit/abb47e8a76251783a1a5a8e15a26b87b2b80f21d.

3. Create an auto-installing image using [autoinstall(8)](https://man.openbsd.org/autoinstall.8). I see two problems here: This is more complicated than it sounds because it would most probably need modifications of OpenBSD's installer, for example to find the install script and sets on the disk image and to install the cloud agent/init tool, and would probably take a bit too long on first boot to install all sets. I will give it a try and test how long it takes to auto-install sets in AWS. The benefit is that this would be closest to a "real" installation process.

For the 2nd method, I created two experimental public AMIs in eu-west-1:
- __[ami-6d03e214](https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#LaunchInstanceWizard:ami=ami-6d03e214)__ for 6.1-current using KARL (see dmesg in https://gist.github.com/reyk/5a6bc5b8ea052f396c1e72b10b1f2175) for 6.1-current with KARL
- __[ami-2300e15a](https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#LaunchInstanceWizard:ami=ami-2300e15a)__ for 6.1-stable using syspatch (see dmesg in https://gist.github.com/reyk/99110eae8e5db14c3cd35c1b006bf63d).

**Comment by reyk** [comment]
* [ami-5e846427](https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#LaunchInstanceWizard:ami=ami-5e846427) for 6.1 auto-installer with syspatch (see dmesg in https://gist.github.com/reyk/55fa601a5b8461e2040d00d5d5f787f4).

Time to close this issue.
