### ISSUE TITLE
Log file for ec2-init.sh

### ISSUE THREAD

**Issue by lbernail** [ajacoutot/aws-openbsd#29]
It would be great if all outputs from ec2-init were logged into a file (to avoid parsing dmesg)
(similar behavior to cloudinit-output.log)

**Comment by anamorph** [comment]
+1

**Comment by ajacoutot** [comment]
Fixed in https://github.com/ajacoutot/aws-openbsd/commit/4d23166a9ae809284739c275c7aecdfd0475254c
Note that it does log much for now (only the SSH fingerprints), but we could extend further if needed.
Sorry for the latency but I am am slackanovist :-)
