### ISSUE TITLE
mount_ffs: /dev/wd0k on /tmp: Device busy

### ISSUE THREAD

**Issue by gretel** [ajacoutot/aws-openbsd#33]
thanks for putting this together.
i ran into something i dont understand - trying both `openbsd-5.3` and `openbsd-snapahot`.
```
openbsd-63# umount -f /tmp
openbsd-63# mount -o "rw,nodev,nosuid" /dev/wd0k /tmp
mount_ffs: /dev/wd0k on /tmp: Device busy
```
```
openbsd-63# df -h
Filesystem     Size    Used   Avail Capacity  Mounted on
/dev/wd0a     1005M   75.9M    879M     8%    /
/dev/wd0k      9.9G   22.0K    9.4G     0%    /home
/dev/wd0f      1.9G    694M    1.2G    37%    /usr
/dev/wd0g     1005M    178M    777M    19%    /usr/X11R6
/dev/wd0h      4.2G   60.0M    4.0G     1%    /usr/local
/dev/wd0j      3.8G    2.0K    3.6G     0%    /usr/obj
/dev/wd0i      1.7G    2.0K    1.6G     0%    /usr/src
/dev/wd0e      2.9G    6.0M    2.7G     0%    /var
/dev/wd0d      1.8G   12.0K    1.8G     0%    /tmp

openbsd-63# disklabel wd0
# /dev/rwd0c:
type: ESDI
disk: ESDI/IDE disk
label: VBOX HARDDISK
duid: 6fabe8bb88d4fb82
flags:
bytes/sector: 512
sectors/track: 63
tracks/cylinder: 255
sectors/cylinder: 16065
cylinders: 3916
total sectors: 62914560
boundstart: 64
boundend: 62910540
drivedata: 0

16 partitions:
#                size           offset  fstype [fsize bsize   cpg]
  a:          2097152               64  4.2BSD   2048 16384 12958 # /
  b:          2588544          2097216    swap                    # none
  c:         62914560                0  unused
  d:          3945920          4685760  4.2BSD   2048 16384 12958 # /tmp
  e:          6176576          8631680  4.2BSD   2048 16384 12958 # /var
  f:          4155776         14808256  4.2BSD   2048 16384 12958 # /usr
  g:          2097152         18964032  4.2BSD   2048 16384 12958 # /usr/X11R6
  h:          9034944         21061184  4.2BSD   2048 16384 12958 # /usr/local
  i:          3587424         30096128  4.2BSD   2048 16384 12958 # /usr/src
  j:          8141536         33683552  4.2BSD   2048 16384 12958 # /usr/obj
  k:         21085440         41825088  4.2BSD   2048 16384 12958 # /home
```
looks like `/dev/wd0k` is mounted as `home`..
```
minimum 12GB free space of /tmp (8GB for disk image and ~4GB for temporary files).
```
so `/tmp` is supposed to.. come from where?

**Comment by ajacoutot** [comment]
On Sun, Apr 29, 2018 at 08:57:32AM -0700, Tom Hensel wrote:
> thanks for putting this together. i ran into something i dont understand - trying both
> openbsd-5.3 and openbsd-snapahot.

> 
> openbsd-63# umount -f /tmp
> openbsd-63# mount -o "rw,nodev,nosuid" /dev/wd0k /tmp
> mount_ffs: /dev/wd0k on /tmp: Device busy

Why are you mounting /tmp ?
It's in used by pretty much everything, no wonder it's busy :-)



> 
> diskaopenbsd-63# disklabel wd0
> # /dev/rwd0c:
> type: ESDI
> disk: ESDI/IDE disk
> label: VBOX HARDDISK
> duid: 6fabe8bb88d4fb82
> flags:
> bytes/sector: 512
> sectors/track: 63
> tracks/cylinder: 255
> sectors/cylinder: 16065
> cylinders: 3916
> total sectors: 62914560
> boundstart: 64
> boundend: 62910540
> drivedata: 0
> 
> 16 partitions:
> #                size           offset  fstype [fsize bsize   cpg]
>   a:          2097152               64  4.2BSD   2048 16384 12958 # /
>   b:          2588544          2097216    swap                    # none
>   c:         62914560                0  unused
>   d:          3945920          4685760  4.2BSD   2048 16384 12958 # /tmp
>   e:          6176576          8631680  4.2BSD   2048 16384 12958 # /var
>   f:          4155776         14808256  4.2BSD   2048 16384 12958 # /usr
>   g:          2097152         18964032  4.2BSD   2048 16384 12958 # /usr/X11R6
>   h:          9034944         21061184  4.2BSD   2048 16384 12958 # /usr/local
>   i:          3587424         30096128  4.2BSD   2048 16384 12958 # /usr/src
>   j:          8141536         33683552  4.2BSD   2048 16384 12958 # /usr/obj
>   k:         21085440         41825088  4.2BSD   2048 16384 12958 # /home
> 
> please assist. regards
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Antoine

**Comment by gretel** [comment]
@ajacoutot sure, but i'm following the instruction in the `README`.

can you explain to me what is supposed to happen? thanks

**Comment by ajacoutot** [comment]
Ah, that's the vagrant part. I have no idea about this... sorry :-/
Please see with Artur Pedziwilk <artur.pedziwilk@netcentric.biz>, he's the one who came up with the extended README. Maybe the documentation needs updating.
I don't use vagrant to build my AMI, I just run the script directly.

**Comment by gretel** [comment]
@ajacoutot thanks, i wasn't aware of skipping vagrant is an option.

could you possibly add your way of building to the `README`?

**Comment by ajacoutot** [comment]
Yeah I need to review this. I have other changes pending anyway but I need to find time... :-/
For the time being, just run the script with whatever option you need/want:

> \# export AWS_ACCESS_KEY_ID=XXX
\# export AWS_SECRET_ACCESS_KEY=YYY
\# ./create-ami.sh -h


Usage:
> \# ./create-ami.sh -h
./create-ami.sh[276]: -h: unknown option
usage: create-ami.sh
       -d "description"
       -i "/path/to/image"
       -n only create the RAW/VMDK images (not the AMI)
       -r "release" (e.g 6.0; default to current)

**Comment by gretel** [comment]
@ajacoutot ah, thanks. i was on the wrong path.
reading `create-ami.sh` - i should be able to circumvent disk size issues by setting `TMPDIR` to something else, like `~/tmp`, right?

**Comment by ajacoutot** [comment]
Note ~/tmp but /tmp.
You can indeed change the default value by exporting TMPDIR to some other directory.
