### ISSUE TITLE
Need to wait for volume converted before creating snapshot

### ISSUE THREAD

**Issue by twwlogin** [ajacoutot/aws-openbsd#34]
After uploading the image to S3 and converting the volume, a snapshot is taken. However, after the image is uploaded to S3, we must wait until the volume is converted before the snapshot is taken.

**Comment by twwlogin** [comment]
I attempted a [patch](https://gist.github.com/twwlogin/f483aca706376f08f799db7a61335979).

**Comment by ajacoutot** [comment]
Hi @twwlogin 
Did you run into any issue that made you write this patch?

**Comment by twwlogin** [comment]
Yes. ec2-describe-conversion-tasks showed an entry like:
         {
            "ConversionTaskId": "import-vol-0a790ded8891e4306", 
            "ImportVolume": {
                "BytesConverted": 0, 
                "Volume": {
                    "Id": "vol-033be82975387451c", 
                    "Size": 9
                }, 
                "Image": {
                    "Size": 443630592, 
                    "ImportManifestUrl": "<url>"", 
                    "Format": "VMDK"
                }, 
                "AvailabilityZone": "us-west-2c", 
                "Description": "openbsd-6.4-amd64-20190129T183210Z"
            }, 
            "ExpirationTime": "2019-02-05T03:35:36Z", 
            "State": "active", 
            "StatusMessage": "Progress: 20%"
        },

but create-ami.sh never waits until "State" is "completed" before creating the snapshot. There is code in create-ami.sh to wait for "completed" after creating a snapshot but not after converting to a volume.

**Comment by ajacoutot** [comment]
Alright thanks.
I'll try and have a look in the next few days.

**Comment by ajacoutot** [comment]
Pushed, thanks. FYI I'm currently reworking this script completely.
And sorry for the latency...

**Comment by twwlogin** [comment]
Thanks. Actually, I was thinking of doing a rewrite as well but looking forward to what you are doing.
