### ISSUE TITLE
running this from a obsd < v6.5  (name too long and no wait argument errors)

### ISSUE THREAD

**Issue by DrmCtchr** [ajacoutot/aws-openbsd#36]
The version of vmctl in previous versions of obsd (sic. less than 6.5 which at this time is still beta) requires you to alter the file obsd-img-builder.sh by replacing "vmctl wait" with "vmctl status" (and code to keep checking OR increase the previous sleep to 30 seconds or so) as wait was not a argument of vmctl until the version in 6.5. You will likely have to use the -i <imagename> argument as well as the default time stamp contained in the name constructed by the script is too long for the old versions of vmctl

**Comment by DrmCtchr** [comment]
well status allows it to complete .... but it really hasnt done anything bah.

**Comment by DrmCtchr** [comment]
just turnsout it was easier to upgrade my installer 6.4 box to 6.5 and rerun....

**Comment by ajacoutot** [comment]
Hi. @DrmCtchr , as mentioned in the README, you need current.
