### ISSUE TITLE
all roads lead to hang mid installation

### ISSUE THREAD

**Issue by DrmCtchr** [ajacoutot/aws-openbsd#37]
the automated installation fo the guest always hangs at the last line of the following.

OpenBSD 6.5 (RAMDISK_CD) #804: Tue Apr  2 20:45:28 MDT 2019
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/RAMDISK_CD
real mem = 520093696 (496MB)
avail mem = 500412416 (477MB)
waiting for vm openbsd-current-amd64-20190405T070721Z: mainbus0 at root
bios0 at mainbus0
acpi at bios0 not configured
cpu0 at mainbus0: (uniprocessor)
cpu0: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 3698.31 MHz, 06-3a-09
cpu0: FPU,VME,DE,PSE,TSC,MSR,PAE,CX8,SEP,PGE,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,SSE3,PCLMUL,SSSE3,CX16,SSE4.1,SSE4.2,POPCNT,AES,XSAVE,AVX,F16C,RDRAND,HV,NXE,LONG,LAHF,ITSC,FSGSBASE,SMEP,ERMS,MELTDOWN
cpu0: 256KB 64b/line 8-way L2 cache
pvbus0 at mainbus0: OpenBSD
pci0 at mainbus0 bus 0
pchb0 at pci0 dev 0 function 0 "OpenBSD VMM Host" rev 0x00
virtio0 at pci0 dev 1 function 0 "Qumranet Virtio RNG" rev 0x00
viornd0 at virtio0
virtio0: irq 3
virtio1 at pci0 dev 2 function 0 "Qumranet Virtio Network" rev 0x00
vio0 at virtio1: address fe:e1:bb:d1:3a:a0
virtio1: irq 5
virtio2 at pci0 dev 3 function 0 "Qumranet Virtio Storage" rev 0x00
vioblk0 at virtio2
scsibus0 at vioblk0: 2 targets
sd0 at scsibus0 targ 0 lun 0: <VirtIO, Block Device, > SCSI3 0/direct fixed
sd0: 10240MB, 512 bytes/sector, 20971520 sectors
virtio2: irq 6
virtio3 at pci0 dev 4 function 0 "Qumranet Virtio Storage" rev 0x00
vioblk1 at virtio3
scsibus1 at vioblk1: 2 targets
sd1 at scsibus1 targ 0 lun 0: <VirtIO, Block Device, > SCSI3 0/direct fixed
sd1: 1024MB, 512 bytes/sector, 2097152 sectors
virtio3: irq 7
virtio4 at pci0 dev 5 function 0 "OpenBSD VMM Control" rev 0x00
vmmci0 at virtio4
virtio4: irq 9
isa0 at mainbus0
com0 at isa0 port 0x3f8/8 irq 4: ns16450, no fifo
com0: console

< at this point we are now hung ... i will let it run the rest of the night in case I'm impatient... but i have tried for a at least 30 minutes earlier ... doesnt matter the release or anything else.

**Comment by mbelop** [comment]
What version of OpenBSD do you run on a host?

What's vmd configuration on the host?

Have you tried an earlier snapshot?

**Comment by DrmCtchr** [comment]
this was from a 6.5 snapshot from cdn.openbsd.org/pub/OpenBSD/snapshots/amd64

the info i have now gathered this seems environmental  i was building this inside a vmm inside a vmware pro 15 VM on a windows machine.... it didnt seem to like it. I am doing the same thing inside a VMware Fusion container on a mac os box and it gets a lot further ...  And yes I have tried 63 64 and snapshots. 

we can likely close this as 'environmental' =]

**Comment by ajacoutot** [comment]
Yeah, this script leverages vmm(4) for autoinstallation. If vmm(4) isn't functional in a particular environment (hardware etc.), there's not much I can do.
Thanks.
