### ISSUE TITLE
File download in autoinstall

### ISSUE THREAD

**Issue by fte378** [ajacoutot/aws-openbsd#39]
I have to run this in a VmWare machine (because I have no hardware running OpenBSD).

The download of the system sets is extremely slow (possibly because of the doubled virtualization), so I wonder if it would be better to download the installation ISO inside the script first and do the autoinstall in the VM from there.
Downloads inside the installation machine (my VmWare machine) run fast.

Any thoughts about this?

**Comment by ajacoutot** [comment]
Hi @fte378 
That's actually a good idea. Could you try the latest code in the "iso" branch and see how it works for you.

**Comment by fte378** [comment]
Thanks for the quick reply. I will try this and come back with the results.

**Comment by ajacoutot** [comment]
Hold on, just spot a small regression

**Comment by ajacoutot** [comment]
> Hold on, just spot a small regression

Fixed, you should be good for testing.

**Comment by fte378** [comment]
I didn't measure the exact times but this cuts out at least 1,5 hours for me!
Great work!

**Comment by fte378** [comment]
Hm. It looks like authentication by public key does not work.

**Comment by ajacoutot** [comment]
> Hm. It looks like authentication by public key does not work.

Make sure you have the latest commit. As I said I had to fix a regression.

**Comment by fte378** [comment]
I'm at 2294913fff2def896f4720f1a6fbcef9677fe447 - this should be the latest commit.

I changed the description fix (not contained in iso branch) and I removed all X11 sets and games.

I will try to get a password login enabled and inspect the generated machine.

**Comment by fte378** [comment]
Forget what I wrote - I have two keys named very similar. I simply used the wrong one.

All works perfectly!

**Comment by ajacoutot** [comment]
Awesome :-)
I'm going to merge it into master, this way is simpler.
Thanks for making me look into it :-)
