### ISSUE TITLE
[Question] ARM image

### ISSUE THREAD

**Issue by ngortheone** [ajacoutot/aws-openbsd#41]
Hi @ajacoutot 

What would help to create an ARM image? Do I need a physical ARM box with OpenBSD on it?

I am willing to offer some help and I know AWS well but my OpenBSD knowledge is very limited.

**Comment by ajacoutot** [comment]
Hi @ngortheone 
You can probably adapt the script in the deprecated folder (to manually create the image install of relying on vmm(4) and autoinstall.
That said, I have no idea whether our arm64 architecture works fine in AWS...
amd64 support is already not working anymore with newer types of instances.
