### ISSUE TITLE
Can not install on t3.micro Instance (free tier)

### ISSUE THREAD

**Issue by johnwmail** [ajacoutot/aws-openbsd#42]
Hi, after uploaded to the my aws account (Region: HK), I can see the AMI, but I cannot install it on t3.micro instance (free tier)?
And only can install it on d2 instance.
Any idea why will that?

![image](https://user-images.githubusercontent.com/1752235/157450306-c63e1d71-0c1c-48af-9fdf-d8f946a817a8.png)

![image](https://user-images.githubusercontent.com/1752235/157450360-2cd2ee4d-d3ae-44af-b531-cd4bdb40c978.png)

**Comment by ajacoutot** [comment]
Hi @johnwmail 
Yes there's no support for these instances; OpenBSD only boots on old-style ones for now.

**Comment by johnwmail** [comment]
Hi, I can install on other region now (SG), but the image seems cannot boot openbsd correctly.
I build the image with this ./obsd-img-builder.sh -r "7.0" 
Any idea? thanks. 
![image](https://user-images.githubusercontent.com/1752235/157573420-13bb84ed-1725-425c-9df7-eb40824049bd.png)

**Comment by johnwmail** [comment]
Actually, I also cannot boot the raw image on local qemu (linux kvm/qemu host).
![image](https://user-images.githubusercontent.com/1752235/157575248-f9d7e053-87aa-44c0-856e-22fd2da708a7.png)

**Comment by johnwmail** [comment]
Ok, it was my mistake, it work now, thanks.
